### ISSUE TITLE
apt-web.dahsy.at jatuh

### ISSUE THREAD

**Issue by Malsasa** [fajran/apt-web#2]
Mas Fajran, kami di Indonesia berulang kali mencoba akses web ajaib ini. Namun selalu gagal. Kami hanya bisa memakai http://repo.ugm.ac.id/apt-web/index.php. Apakah memang web ini sementara dinonaktifkan? Terima kasih.

**Comment by herpiko** [comment]
@Malsasa Ini baru hidup yang v2 golang :smile:  http://128.199.95.141:8080/
Lagi lobi2 supaya bisa hidup di  apt-web.blankon.in. Nanti saya butuh bantuan Pak @Malsasa untuk kumpulin berkas status lagi, seperti dulu.

**Comment by fajran** [comment]
Hidup oom @herpiko!
